# Generated by Django 4.1.3 on 2022-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=256, null=True, verbose_name='Comprador')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descricao')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Preço Unitário')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=9, null=True, verbose_name='Quantidade')),
                ('address', models.CharField(max_length=256, null=True, verbose_name='Endereço')),
                ('supplier', models.CharField(max_length=256, null=True, verbose_name='Fornecedor')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
